config {
  type: "table",
  schema: "gold",
  name: "gold_users_address",
  description: "user profile combining latest user attributes with corresponding address details",
  uniqueKey: ["user_id"],
  dependencies: ["bootstrap", "silver_users", "silver_address"],
  bigquery: {
    partitionBy: "DATE(_ingested_at)",
    clusterBy: ["city"]
    }
}

SELECT
  u.user_id,
  u.first_name,
  u.last_name,
  a.country,
  a.region,
  a.city,
  a.address,
  greatest(u._ingested_at, a._ingested_at) as _ingested_at
FROM ${ref("silver_users")} AS u
LEFT JOIN ${ref("silver_address")} AS a
ON u.user_id = a.user_id
